### ISSUE TITLE
문제 발견! 찾았다 범인

### ISSUE THREAD

**Issue by jws020501** [kwb020312/ChobbyRoom#1]
스크롤시 **선입력 딜레이**가 너무 심하네요 **수정**부탁드려용~~~

**Comment by kwb020312** [comment]
> 스크롤시 **선입력 딜레이**가 너무 심하네요 **수정**부탁드려용~~~

오픈 소스인 만큼 수정해서 Pull Request 올려주시면 감사하겠습니다.
